baseURL = 'https://www.insileco.io/'
languageCode = 'en-us'
title = 'inSileco'
theme = ["github.com/StefMa/hugo-fresh"]
googleAnalytics = ""
defaultContentLanguage = "en"
enableEmoji = true

[module.imports]
path = "github.com/StefMa/hugo-fresh"

[markup.goldmark.renderer]
unsafe = true


[languages.en]
weight = 1
title = "inSileco"

[languages.fr]
weight = 2
title = "inSileco"

[languages.fr.params]

[languages.fr.params.hero]
title = "inSileco"
subtitle = "Le site est actuellement en construction"
buttontext = "Commencer"
buttonlink = "#"
image = "logo.svg"

[[languages.fr.params.navbar]]
title = "A propos"
url = "/fr/about"

[[languages.fr.params.navbar]]
title = "Éducation"
url = "/fr/education"

[[languages.fr.params.navbar]]
title = "Éducation"
url = "/fr/education"

[[languages.fr.params.navbar]]
title = "Blogue (en)"
url = "https://blog.insileco.io/"
#button = true


[params]
openGraph = true

[params.navbarlogo]
image = "logo.svg"
link = "/"

[params.font]
name = "Open Sans"
sizes = [400, 600]


[params.hero]
title = "inSileco"
subtitle = "This is work in progress"
buttontext = "Get started"
buttonlink = "#"
image = "logo.svg"

[[params.hero.clientlogos]]
logo = "systek"
url = "https://google.com"

[[params.hero.clientlogos]]
logo = "tribe"
url = "https://stefma.github.io/hugo-fresh/"

[[params.hero.clientlogos]]
logo = "kromo"
url = "https://github.com/StefMa/hugo-fresh"

[[params.hero.clientlogos]]
logo = "infinite"
url = "https://hugo-fresh.vercel.app/"

[[params.hero.clientlogos]]
logo = "gutwork"
url = "https://bulma.io/"

[[params.navbar]]
title = "About"
url = "/about"

[[params.navbar]]
title = "Education"
url = "/education"

[[params.navbar]]
title = "Projects"
url = "/projects"

[[params.navbar]]
title = "Blog"
url = "https://blog.insileco.io/"
#button = true

[params.sidebar]
logo = "fresh-square"

[[params.sidebar.sections]]
title = "User"
icon = "user"

[[params.sidebar.sections.links]]
text = "Profile"
url = "/"

[[params.sidebar.sections.links]]
text = "Account"
url = "/"

[[params.sidebar.sections.links]]
text = "Settings"
url = "/"

[[params.sidebar.sections]]
title = "Messages"
icon = "envelope"

[[params.sidebar.sections.links]]
text = "Inbox"
url = "/"

[[params.sidebar.sections.links]]
text = "Compose"
url = "/"

[[params.sidebar.sections]]
title = "Images"
icon = "image"

[[params.sidebar.sections.links]]
text = "Library"
url = "/"

[[params.sidebar.sections.links]]
text = "Upload"
url = "/"

[[params.sidebar.sections]]
title = "Settings"
icon = "cog"

[[params.sidebar.sections.links]]
text = "User settings"
url = "/"

[[params.sidebar.sections.links]]
text = "App settings"
url = "/"

[params.section1]
title = "Data Science"
subtitle = ""

[[params.section1.tiles]]
title = "App builder"
icon = "mouse-globe"
text = "This is some explanatory text that is on two rows"
url = "/"
buttonText = "Free trial"

[[params.section1.tiles]]
title = "Cloud integration"
icon = "laptop-cloud"
text = "This is some explanatory text that is on two rows"
url = "/"
buttonText = "Get started"

[[params.section1.tiles]]
title = "Add-ons & plugins"
icon = "plug-cloud"
text = "This is some explanatory text that is on two rows"
url = "/"
buttonText = "Get started"


[params.section2]
title = "You're here because you want the best"
subtitle = "And we know it"

[[params.section2.features]]
title = "Powerful and unified interface"
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis."
icon = "laptop-globe"

[[params.section2.features]]
title = "Cross-device synchronisation"
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis."
icon = "doc-sync"

[[params.section2.features]]
title = "Nomad system"
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis."
icon = "mobile-feed"

[params.section3]
title = "One platform"
subtitle = "To rule them all"
image = "illustrations/mockups/app-mockup.png"
buttonText = "Get started"
buttonLink = "#"

[params.section4]
title = "Our Clients love us!"
subtitle = "Lorem ipsum sit dolor amet is a dummy text used by typography industry"

[[params.section4.clients]]
name = "Irma Walters"
quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
job = "Accountant"
img = 1

[[params.section4.clients]]
name = "John Bradley"
quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
job = "Financial Analyst"
img = 2

[[params.section4.clients]]
name = "Gary Blackman"
quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
job = "HR Manager"
img = 3

# [params.section5]
# title = "Drop us a line or two"
# subtitle = "We'd love to hear from you"
# buttonText = "Send Message"



[params.footer]
logo = "logo.svg"
socialmediatitle = "Follow Us"
bulmalogo = true

[[params.footer.socialmedia]]
link = "https://github.com/inSilecoInc"
icon = "github"


[[params.footer.socialmedia]]
link = "https://facebook.com/#"
icon = "facebook"

[[params.footer.socialmedia]]
link = "https://twitter.com/insileco"
icon = "twitter"

[[params.footer.socialmedia]]
link = "https://bitbucket.org/#"
icon = "bitbucket"

[params.footer.quicklinks.column1]
title = "Projects"

[[params.footer.quicklinks.column1.links]]
text = "Data pipelines"
link = "/"

[[params.footer.quicklinks.column1.links]]
text = "Statistical analysis"
link = "/"

[[params.footer.quicklinks.column1.links]]
text = "Teaching materials"
link = "/"


[params.footer.quicklinks.column2]
title = "Workshops"

[[params.footer.quicklinks.column2.links]]
text = "Learning git"
link = "/"

[[params.footer.quicklinks.column2.links]]
text = "R as a GIS"
link = "/"


[params.footer.quicklinks.column3]
title = "Blog"

[[params.footer.quicklinks.column3.links]]
text = "Latest posts"
link = "https://blog.insileco.io/post/"

[[params.footer.quicklinks.column3.links]]
text = "Resources"
link = "https://blog.insileco.io/resource/"

[[params.footer.quicklinks.column3.links]]
icon = "github"
link = "https://github.com/inSileco"

