baseURL = 'https://insileco.io/'
languageCode = 'en'
title = 'inSileco'

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = ["perso.css"]
custom_js = []

[languages]
  [languages.fr]
    languageCode = "fr-ca"
    weight = 1
    contentDir = "content/fr"
    [languages.fr.params]
        subtitle = "Gestion écosystémique & Science des données"
        keywords = ["Solutions", "Accompagnement", "Formations"]
        title_expertise = "Notre expertise"
        subtitle_expertise = "Quand la science des données rencontre la gestion environnementale"
        title_team = "Notre équipe"
        subtitle_team = ""
        footer = 'Le code source de ce site est sous licence <a href="http://opensource.org/licenses/mit-license.php">MIT</a> et disponible sur <a href="https://github.com/inSilecoInc/insilecoinc.github.io">GitHub</a>. &copy; inSileco 2023'
    [[languages.fr.menu.main]]
        name = "Mission"
        url = "#mission"
        weight = 1
    [[languages.en.menu.main]]
        name = "Notre expertise"
        url = "#expertise"
        weight = 2
    [[languages.fr.menu.main]]
        name = "Équipe"
        url = "#team"
        weight = 3
    [[languages.fr.menu.main]]
        name = "Démarche"
        url = "#approach"
        weight = 4
    [[languages.en.menu.main]]
        name = "Publications"
        url = "/publications/"
        weight = 5
    [[languages.fr.menu.main]]
        name = "Blogue"
        url = "https://blog.insileco.io"
        weight = 6
    [[languages.fr.menu.main]]
        name = "Contactez-nous"
        url = "#contact"
        weight = 7
  [languages.en]
    languageCode = "en-ca"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
        subtitle = "Environmental management & Data science"
        keywords = ["Solutions", "Support", "Training"]
        title_expertise = "Our expertise"
        subtitle_expertise = "Where data science meets environmental management"
        title_team = "Our team"
        subtitle_team = ""
        footer = 'The source code of this website is licensed <a href="http://opensource.org/licenses/mit-license.php">MIT</a> and available on <a href="https://github.com/inSilecoInc/insilecoinc.github.io">GitHub</a>. &copy; inSileco 2023.'
    [[languages.en.menu.main]]
        name = "Mission"
        url = "#mission"
        weight = 1
    [[languages.en.menu.main]]
        name = "Our expertise"
        url = "#expertise"
        weight = 2
    [[languages.en.menu.main]]
        name = "Team"
        url = "#team"
        weight = 3
    [[languages.en.menu.main]]
        name = "Approach"
        url = "#approach"
        weight = 4
    [[languages.en.menu.main]]
        name = "Publications"
        url = "/publications/"
        weight = 5
    [[languages.en.menu.main]]
        name = "Blog"
        url = "https://blog.insileco.io"
        weight = 6
    [[languages.en.menu.main]]
        name = "Contact us"
        url = "#contact"
        weight = 7

[params]
col_emphase = "#b4637a"
