baseURL = 'https://insileco.io/'
languageCode = 'en'
title = 'inSileco'


[languages]
  [languages.fr]
    languageCode = "fr-ca"
    weight = 1
    contentDir = "content/fr"
    [languages.fr.params]
        subtitle = "Cabinet de consultants en science des données"
        keywords = ["Solutions", "Accompagnement", "Formations"]
        title_portfolio = "Nos Réalisations"
        title_team = "Notre équipe"
        subtitle_team = "Prête à vous accompagner pour relever vos défis en science des données"
        footer = 'Le code source de ce site est sous licence <a href="http://opensource.org/licenses/mit-license.php">MIT</a> et disponible sur <a href="https://github.com/inSilecoInc/insilecoinc.github.io">GitHub</a>. &copy; inSileco 2023'
    [[languages.fr.menu.main]]
        name = "Mission"
        url = "#mission"
        weight = 1
    [[languages.fr.menu.main]]
        name = "Nos réalisations"
        url = "#portfolio"
        weight = 2
    [[languages.fr.menu.main]]
        name = "Équipe"
        url = "#team"
        weight = 3
    [[languages.fr.menu.main]]
        name = "Démarche"
        url = "#approach"
        weight = 4
    [[languages.fr.menu.main]]
        name = "Blogue"
        url = "https://blog.insileco.io"
        weight = 5
    [[languages.fr.menu.main]]
        name = "Contactez-nous"
        url = "#contact"
        weight = 6
  [languages.en]
    languageCode = "en-ca"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
        subtitle = "Data science consulting"
        keywords = ["Solutions", "Support", "Trainings"]
        title_portfolio = "Our work"
        title_team = "Our team"
        subtitle_team = "Ready to support you in meeting your data science challenges"
        footer = 'The source code of this website is licensed <a href="http://opensource.org/licenses/mit-license.php">MIT</a> and available on <a href="https://github.com/inSilecoInc/insilecoinc.github.io">GitHub</a>. &copy; inSileco 2023.'
    [[languages.en.menu.main]]
        name = "Mission"
        url = "#mission"
        weight = 1
    [[languages.en.menu.main]]
        name = "Our work"
        url = "#portfolio"
        weight = 2
    [[languages.en.menu.main]]
        name = "Team"
        url = "#team"
        weight = 3
    [[languages.en.menu.main]]
        name = "Approach"
        url = "#approach"
        weight = 4
    [[languages.en.menu.main]]
        name = "Blog"
        url = "https://blog.insileco.io"
        weight = 5
    [[languages.en.menu.main]]
        name = "Contact us"
        url = "#contact"
        weight = 6